language: rust
cache: cargo

env: RUSTFLAGS="--cfg procmacro2_semver_exempt" # required for cargo-tarpaulin

after_success:
  - cargo install cargo-tarpaulin || echo "cargo-tarpaulin already installed"
  - cargo tarpaulin --out Xml
  - bash <(curl -s https://codecov.io/bash) -X gcov
