[package]
name = "url-bot"
version = "0.1.0"
authors = ["Edward Cragg <drq.11235@gmail.com>"]

[dependencies]
irc = "0.12"
hyper = "0.11.14"
tokio-core = "0.1"
curl = "0.4.11"
htmlescape = "0.3.1"
regex = "*"
rusqlite = "0.13.0"
time = "0.1.40"
docopt = "1.0.0"
serde = "1.0.70"
serde_derive = "1.0.70"
